// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductInventory.Data;

#nullable disable

namespace ProductInventory.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20231017123718_initial config")]
    partial class initialconfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("ProductInventory.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Tool",
                            Name = "Hammer",
                            Price = 121.50m
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Tool",
                            Name = "Angle grinder",
                            Price = 1520.00m
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Vehicle",
                            Name = "Mini Cooper",
                            Price = 990000m
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Vehicle",
                            Name = "Chevrolet Camaro",
                            Price = 620000m
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Groceries",
                            Name = "Milk",
                            Price = 14.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
